// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5kcraCOL9EDhx6K-eNhj4JMkGhSEo0Z0',
    appId: '1:114222355553:web:2273af934a540ca6fb0620',
    messagingSenderId: '114222355553',
    projectId: 'primeiro-projeto-44307',
    authDomain: 'primeiro-projeto-44307.firebaseapp.com',
    storageBucket: 'primeiro-projeto-44307.firebasestorage.app',
    measurementId: 'G-MMZJ04ZF0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXjM7q_pSWEGiYtm4gH2N08cf78MlT3Cs',
    appId: '1:114222355553:android:22596bacaf37dac7fb0620',
    messagingSenderId: '114222355553',
    projectId: 'primeiro-projeto-44307',
    storageBucket: 'primeiro-projeto-44307.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5kcraCOL9EDhx6K-eNhj4JMkGhSEo0Z0',
    appId: '1:114222355553:web:02a5c6b5ea105f67fb0620',
    messagingSenderId: '114222355553',
    projectId: 'primeiro-projeto-44307',
    authDomain: 'primeiro-projeto-44307.firebaseapp.com',
    storageBucket: 'primeiro-projeto-44307.firebasestorage.app',
    measurementId: 'G-1PYCLFY1WE',
  );

}